apiVersion: v1
kind: Service
metadata:
  name: threats
  namespace: power
  labels:
    app: threats
    service: threats
spec:
  selector:
    app: threats
  ports:
    - name: http
      port: 8081
  type: ClusterIP