apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 1
  labels:
    app: heroes
  name: heroes
  namespace: node
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: heroes
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: heroes
    spec:
      containers:
      - image: xylene1980/heroes_app:latest
        imagePullPolicy: Always
        # ports: 
        #   - containerPort: 8081
        name: heroes
        resources: {}
      imagePullSecrets:
      - name: myregistrykey
status:
  availableReplicas: 1
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
