apiVersion: v1
kind: Service
metadata:
  name: heroes
  namespace: node
  labels:
    app: heroes
    service: heroes
spec:
  selector:
    app: heroes
  ports:
    - name: http
      port: 8081
  type: ClusterIP
  # ports:
  # - protocol: TCP
  #   port: 80
  #   targetPort: 8081
  #   name: http
  # selector:
  #   app: heroes